VERSION="0.1.1"

# configuration environment variables
ENV_COVIGATOR_STORAGE_FOLDER = "COVIGATOR_STORAGE_FOLDER"
ENV_COVIGATOR_DB_PORT = "COVIGATOR_DB_PORT"
ENV_COVIGATOR_DB_PASSWORD = "COVIGATOR_DB_PASSWORD"
ENV_COVIGATOR_DB_USER = "COVIGATOR_DB_USER"
ENV_COVIGATOR_DB_NAME = "COVIGATOR_DB_NAME"
ENV_COVIGATOR_DB_HOST = "COVIGATOR_DB_HOST"