name: Code Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest discover covigator.tests.unit_tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3