name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          #POSTGRES_DB: test_db
          #POSTGRES_USER: test_user
          #POSTGRES_PASSWORD: test_pass
          #POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build, install and run unit tests
      env:
        # The hostname used to communicate with the PostgreSQL service container
        POSTGRES_HOST: localhost
        # The default PostgreSQL port
        POSTGRES_PORT: 5432
        COVIGATOR_DB_NAME: postgres
        COVIGATOR_DB_USER: postgres
        COVIGATOR_DB_PASSWORD: postgres
        COVIGATOR_DB_PORT: 5432
        COVIGATOR_DB_HOST: localhost
      run: |
        python setup.py bdist_wheel
        pip install numpy==1.21.0
        pip install dist/covigator*.whl
        python -m unittest discover covigator.tests.unit_tests