name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build, install and run unit tests
      env:
        # The hostname used to communicate with the PostgreSQL service container
        #POSTGRES_HOST: postgres
        # The default PostgreSQL port
        #POSTGRES_PORT: 5432
        COVIGATOR_DB_NAME: postgres
        COVIGATOR_DB_USER: postgres
        COVIGATOR_DB_PASSWORD: postgres
        COVIGATOR_DB_PORT: ${{ job.services.postgres.ports[5432] }}
        COVIGATOR_DB_HOST: postgres
      run: |
        python setup.py bdist_wheel
        pip install numpy==1.21.0
        pip install dist/covigator*.whl
        python -m unittest discover covigator.tests.unit_tests